// Tempo UI kit. Import from '../components/ui' (views) or './ui' (components). See docs/design.md.
export { cn, type ClassValue } from './cn'
export { EASE, DUR, fadeUp, scaleIn, spring, listStagger, listItem } from './motion'
export { PROJECT_COLOR, colorForName, type ColorClasses, type ProjectColorClasses } from './colors'

export { Button, type ButtonProps, type ButtonVariant, type ButtonSize } from './Button'
export { IconButton, type IconButtonProps } from './IconButton'
export { Input, FIELD_SIZE, type InputProps, type FieldSize } from './Input'
export { Textarea, type TextareaProps } from './Textarea'
export { Select, type SelectProps, type SelectOption } from './Select'
export { Checkbox, type CheckboxProps } from './Checkbox'
export { ProjectDot, type ProjectDotProps } from './ProjectDot'
export { Avatar, initials, type AvatarProps } from './Avatar'
export { AppIcon, appMonogram, type AppIconProps } from './AppIcon'
export { Kbd, MOD, type KbdProps } from './Kbd'
export { Modal, type ModalProps } from './Modal'
export { Drawer, type DrawerProps } from './Drawer'
export { Popover, Menu, type PopoverProps, type MenuProps, type MenuItem } from './Popover'
export { EmptyState, type EmptyStateProps } from './EmptyState'
export { Skeleton, SkeletonText, SkeletonRow, type SkeletonProps } from './Skeleton'
export { Spinner, type SpinnerProps } from './Spinner'
export { ToastHost } from './Toast'
export { ProgressBar, type ProgressBarProps } from './Progress'
export { SegmentedControl, type SegmentedControlProps, type SegmentedOption } from './SegmentedControl'
export { Chip, type ChipProps } from './Chip'
export { Page, PageHeader, SectionHeader, Card, type PageProps, type PageHeaderProps, type SectionHeaderProps, type CardProps } from './Layout'
